import type { KoraAttributeKnowledge } from "./knowledge-types";

export const KORA_ATTRIBUTE_KNOWLEDGE: KoraAttributeKnowledge[] = [
  { id: "bluetooth", label: "Bluetooth", aliases: ["bluetooth", "blutu", "blutú", "conexion bluetooth", "conexión bluetooth", "conectar celular", "sin cables"], explanation: "Bluetooth permite conectar el celular, tablet u otro dispositivo sin cables para reproducir música o audio.", commercialBenefit: "Es ideal si quieres poner música fácil desde el celular.", goodFor: ["casa", "negocio", "reuniones", "karaoke", "fiestas pequeñas"], limitations: "Funciona a corta distancia y para audio profesional estable a veces conviene cable.", salesAngle: "Si el cliente busca practicidad, Bluetooth es clave.", relatedCategories: ["cabinas", "parlantes", "car audio", "teatros en casa"], suggestedFollowups: ["¿Lo quieres para casa, negocio o fiesta?", "¿Quieres que también sea recargable?", "¿Te muestro opciones con Bluetooth?"] },
  { id: "fm", label: "Radio FM", aliases: ["fm", "radio", "emisoras", "sintonizador", "radio integrada"], explanation: "FM permite sintonizar emisoras sin conectar el celular.", commercialBenefit: "Útil para negocio, casa o taller donde escuchan radio a diario.", goodFor: ["negocio", "casa", "tiendas", "talleres"], limitations: "La señal depende de ubicación e interferencias.", salesAngle: "Si quiere emisoras sin depender del celular, FM suma bastante.", relatedCategories: ["cabinas", "radios", "parlantes"], suggestedFollowups: ["¿Lo quieres para emisoras o música del celular?", "¿Será para casa o negocio?"] },
  { id: "usb", label: "USB", aliases: ["usb", "memoria usb", "pendrive", "entrada usb"], explanation: "USB permite reproducir música desde memoria directamente en el equipo.", commercialBenefit: "No dependes del celular o internet para poner música.", goodFor: ["negocios", "fiestas", "casa", "reproducción continua"], limitations: "Depende de formatos de archivo compatibles.", salesAngle: "Si quiere dejar música lista en memoria, USB es práctico.", relatedCategories: ["cabinas", "radios", "parlantes", "car audio"], suggestedFollowups: ["¿Desde memoria o desde celular?", "¿Lo usarías en negocio o personal?"] },
  { id: "auxiliar", label: "Entrada auxiliar", aliases: ["aux", "auxiliar", "entrada 3.5", "jack", "miniplug"], explanation: "La entrada auxiliar conecta audio por cable desde celular, PC u otro equipo.", commercialBenefit: "Conexión estable y sencilla sin depender de Bluetooth.", goodFor: ["casa", "computador", "audio básico", "equipos antiguos"], limitations: "Requiere cable compatible y algunos celulares necesitan adaptador.", salesAngle: "Si prefiere cable directo, AUX resuelve rápido.", relatedCategories: ["cabinas", "parlantes", "amplificadores", "cables"], suggestedFollowups: ["¿Conectarás por cable o Bluetooth?", "¿Qué equipo quieres conectar?"] },
  { id: "recargable", label: "Recargable", aliases: ["recargable", "bateria", "batería", "portatil", "portátil", "sin corriente"], explanation: "Un equipo recargable tiene batería interna y puede usarse sin corriente directa.", commercialBenefit: "Da movilidad para exteriores, reuniones o lugares sin toma cercana.", goodFor: ["fiestas pequeñas", "exteriores", "reuniones", "clases", "karaoke"], limitations: "La duración depende de volumen, luces y uso.", salesAngle: "Si necesita movilidad, recargable es clave.", relatedCategories: ["cabinas", "parlantes portátiles", "luces solares"], suggestedFollowups: ["¿Lo usarás fuera de casa?", "¿Prefieres potencia o portabilidad?", "¿Quieres algo fácil de mover?"] },
  { id: "cabina_activa", label: "Cabina activa", aliases: ["cabina activa", "parlante activo", "bafle activo", "activa"], explanation: "La cabina activa ya trae amplificador interno, así que no necesita planta aparte para funcionar.", commercialBenefit: "Es más fácil de instalar y usar para la mayoría de clientes.", goodFor: ["casa", "fiesta", "negocio", "iglesias pequeñas", "karaoke"], limitations: "Para montajes grandes puede requerir sistema más completo.", salesAngle: "Si quiere comprar y usar sin complicarse, activa suele ser la mejor opción.", relatedCategories: ["cabinas activas", "sonido"], suggestedFollowups: ["¿Para casa, negocio, iglesia o fiesta?", "¿La quieres con Bluetooth?", "¿Recargable o conectada?"] },
  { id: "cabina_pasiva", label: "Cabina pasiva", aliases: ["cabina pasiva", "parlante pasivo", "bafle pasivo", "pasiva"], explanation: "La cabina pasiva no trae amplificador interno y necesita planta/amplificador externo.", commercialBenefit: "Útil para sistemas más profesionales o instalaciones grandes.", goodFor: ["instalaciones", "eventos", "iglesias", "sonido profesional"], limitations: "No funciona sola: requiere amplificador compatible.", salesAngle: "Conviene si ya tiene planta o quiere armar sistema profesional.", relatedCategories: ["cabinas pasivas", "amplificadores"], suggestedFollowups: ["¿Ya tienes amplificador?", "¿Instalación fija o evento?", "¿Prefieres algo más simple como activa?"] },
  { id: "pulgadas_parlante", label: "Pulgadas del parlante", aliases: ["pulgadas", "woofer", "parlante de 12", "parlante de 15", "tamaño parlante"], explanation: "Las pulgadas indican el tamaño del parlante principal (woofer), por ejemplo 8, 10, 12 o 15.", commercialBenefit: "Ayuda a estimar presencia y bajos según el uso.", goodFor: ["cabinas", "fiestas", "negocio", "iglesias", "comparar opciones"], limitations: "No todo depende del tamaño: también importa potencia y calidad.", salesAngle: "Si quiere más cuerpo y bajo, suele convenir mirar 12 o 15 pulgadas.", relatedCategories: ["cabinas", "parlantes", "car audio"], suggestedFollowups: ["¿Espacio pequeño, mediano o grande?", "¿Más volumen o más portabilidad?", "¿Buscas bajo fuerte?"] },
  { id: "potencia", label: "Potencia", aliases: ["potencia", "watts", "w", "vatios", "suena duro", "volumen"], explanation: "La potencia influye en cuánto volumen y energía de sonido entrega el equipo.", commercialBenefit: "Permite orientar si alcanza para casa, negocio, iglesia o fiesta.", goodFor: ["eventos", "fiestas", "iglesias", "negocios"], limitations: "No siempre más watts significa mejor sonido; también importa calidad y tamaño.", salesAngle: "Para sonar duro, hay que mirar potencia más tamaño y calidad del equipo.", relatedCategories: ["cabinas", "amplificadores", "parlantes", "car audio"], suggestedFollowups: ["¿Para cuántas personas?", "¿Interior o exterior?", "¿Más volumen o mejor calidad?"] },
  { id: "bajo", label: "Bajo", aliases: ["bajo", "bass", "retumba", "grave", "subwoofer", "bajo potente"], explanation: "El bajo es la parte grave del sonido que da cuerpo e impacto.", commercialBenefit: "Muy buscado para fiesta, música urbana, car audio y negocio.", goodFor: ["fiestas", "car audio", "cabinas grandes", "subwoofer"], limitations: "Más bajo no siempre es mejor: debe mantenerse claridad.", salesAngle: "Si quiere impacto, mira parlante grande, buena potencia y subwoofer cuando aplique.", relatedCategories: ["cabinas", "subwoofers", "car audio"], suggestedFollowups: ["¿Bajo para fiesta, carro o negocio?", "¿Espacio pequeño o grande?", "¿Prefieres equilibrio o pegada fuerte?"] },
  { id: "microfono_alambrico", label: "Micrófono alámbrico", aliases: ["microfono alambrico", "micrófono alámbrico", "mic con cable", "micro con cable"], explanation: "El micrófono alámbrico se conecta por cable a cabina, consola o amplificador.", commercialBenefit: "Es estable, confiable y normalmente más económico.", goodFor: ["iglesias", "colegios", "karaoke fijo", "conferencias"], limitations: "Limita el movimiento por el cable.", salesAngle: "Si busca economía y estabilidad, alámbrico suele rendir muy bien.", relatedCategories: ["micrófonos", "cables", "consolas"], suggestedFollowups: ["¿Para cantar o hablar?", "¿Una sola persona o varias?", "¿Ya tienes cable compatible?"] },
  { id: "microfono_inalambrico", label: "Micrófono inalámbrico", aliases: ["microfono inalambrico", "micrófono inalámbrico", "sin cable", "wireless"], explanation: "El micrófono inalámbrico transmite sin cable hacia un receptor conectado al sonido.", commercialBenefit: "Da libertad de movimiento en presentaciones, iglesias y karaoke.", goodFor: ["iglesias", "eventos", "karaoke", "presentaciones"], limitations: "Depende de baterías y puede sufrir interferencias según entorno.", salesAngle: "Si necesita moverse mientras habla o canta, inalámbrico es más cómodo.", relatedCategories: ["micrófonos", "sonido profesional"], suggestedFollowups: ["¿Lo usarás para cantar o hablar?", "¿Lo quieres sencillo o doble?", "¿Será para iglesia, evento o karaoke?"] },
  { id: "microfono_sencillo", label: "Micrófono sencillo", aliases: ["microfono sencillo", "un microfono", "un solo mic"], explanation: "Incluye una sola unidad para una persona.", commercialBenefit: "Más económico cuando solo participa una persona a la vez.", goodFor: ["karaoke personal", "clases", "reuniones", "conferencias"], limitations: "Si participan dos personas al tiempo, puede quedarse corto.", salesAngle: "Si lo usa una sola persona, el sencillo es práctico y económico.", relatedCategories: ["micrófonos"], suggestedFollowups: ["¿Lo usará una sola persona?", "¿Lo quieres con cable o inalámbrico?"] },
  { id: "microfono_doble", label: "Micrófono doble", aliases: ["microfono doble", "dos microfonos", "par de microfonos"], explanation: "Incluye dos micrófonos, útil para dos personas al mismo tiempo.", commercialBenefit: "Ideal para karaoke, eventos, entrevistas o presentaciones duales.", goodFor: ["karaoke", "iglesias", "eventos", "entrevistas"], limitations: "Cuesta más que uno sencillo y requiere revisar compatibilidad.", salesAngle: "Si participarán dos personas al tiempo, doble es más conveniente.", relatedCategories: ["micrófonos", "karaoke"], suggestedFollowups: ["¿Será para dos personas al tiempo?", "¿Karaoke, iglesia o evento?"] },
  { id: "amplificador", label: "Amplificador", aliases: ["amplificador", "planta", "power", "etapa"], explanation: "Un amplificador da potencia a parlantes o cabinas pasivas.", commercialBenefit: "Necesario para sistemas pasivos y montajes de mayor control.", goodFor: ["cabinas pasivas", "iglesias", "eventos", "instalaciones"], limitations: "Debe ser compatible con parlantes para evitar fallas.", salesAngle: "Si tiene cabinas pasivas, necesita amplificador bien elegido.", relatedCategories: ["amplificadores", "cabinas pasivas"], suggestedFollowups: ["¿Qué cabinas quieres conectar?", "¿Son activas o pasivas?", "¿Para negocio, iglesia o evento?"] },
  { id: "consola", label: "Consola de sonido", aliases: ["consola", "mixer", "mezclador", "mezcladora", "mesa de mezcla"], explanation: "La consola permite conectar y controlar varias fuentes de audio.", commercialBenefit: "Da control de volúmenes y mezcla para voz, instrumentos y música.", goodFor: ["iglesias", "eventos", "estudios", "karaoke avanzado"], limitations: "Requiere manejo básico para aprovecharla bien.", salesAngle: "Si conectará varios micrófonos/instrumentos, la consola ayuda mucho.", relatedCategories: ["consolas", "micrófonos", "cabinas"], suggestedFollowups: ["¿Cuántos micrófonos conectarás?", "¿Para iglesia, evento o estudio?", "¿Necesitas efectos o Bluetooth?"] },
  { id: "dvr", label: "DVR", aliases: ["dvr", "grabador", "sistema dvr", "cctv", "circuito cerrado"], explanation: "Un DVR recibe y graba la señal de varias cámaras cableadas.", commercialBenefit: "Ideal para sistemas de seguridad más completos con varias cámaras.", goodFor: ["negocios", "bodegas", "oficinas", "casas grandes"], limitations: "Normalmente requiere cableado, disco duro y configuración.", salesAngle: "Si quiere varias cámaras y grabación centralizada, DVR suele convenir.", relatedCategories: ["cámaras de seguridad", "dvr", "kits"], suggestedFollowups: ["¿Cuántas cámaras necesitas?", "¿Casa o negocio?", "¿Prefieres WiFi o cableado?"] },
  { id: "camara_wifi", label: "Cámara WiFi", aliases: ["camara wifi", "cámara wifi", "camara con app", "ver desde celular"], explanation: "La cámara WiFi se conecta a internet y se visualiza desde app en el celular.", commercialBenefit: "Práctica para instalación rápida sin sistema completo.", goodFor: ["casa", "negocio pequeño", "habitación", "monitoreo básico"], limitations: "Depende de señal WiFi estable.", salesAngle: "Si quiere algo fácil de instalar y ver desde el celular, WiFi ayuda.", relatedCategories: ["cámaras wifi", "seguridad"], suggestedFollowups: ["¿Es para casa o negocio?", "¿Necesitas grabación en microSD?", "¿Interior o exterior?"] },
  { id: "vision_nocturna", label: "Visión nocturna", aliases: ["vision nocturna", "visión nocturna", "infrarrojo", "ir", "ve de noche"], explanation: "Permite a la cámara capturar imagen en poca luz u oscuridad.", commercialBenefit: "Clave para vigilancia nocturna real.", goodFor: ["entradas", "patios", "negocios", "bodegas", "exteriores"], limitations: "Claridad y distancia dependen del modelo y entorno.", salesAngle: "Si necesita seguridad de noche, visión nocturna es importante.", relatedCategories: ["cámaras", "dvr", "seguridad"], suggestedFollowups: ["¿Interior o exterior?", "¿La zona es muy oscura?", "¿Necesitas grabación continua?"] },
  { id: "micro_sd", label: "MicroSD", aliases: ["micro sd", "microsd", "tarjeta sd", "memoria para camara"], explanation: "MicroSD es una memoria pequeña para guardar videos o archivos en equipos compatibles.", commercialBenefit: "En cámaras WiFi permite grabar sin DVR.", goodFor: ["cámaras wifi", "hogar", "monitoreo sencillo"], limitations: "La capacidad define cuánto guarda y puede sobrescribir antiguos.", salesAngle: "Si quiere cámara sencilla con grabación local, revisar microSD.", relatedCategories: ["cámaras wifi", "seguridad", "memorias"], suggestedFollowups: ["¿Quieres grabar o solo ver en vivo?", "¿Prefieres WiFi o DVR?"] },
  { id: "pulgadas_tv", label: "Pulgadas de TV", aliases: ["pulgadas tv", "tamaño televisor", "televisor de 32", "televisor de 43", "televisor de 50"], explanation: "Las pulgadas del TV indican el tamaño diagonal de pantalla.", commercialBenefit: "Ayuda a elegir según espacio y distancia de visualización.", goodFor: ["sala", "habitación", "negocio", "entretenimiento"], limitations: "Más grande no siempre es mejor para espacios pequeños.", salesAngle: "Para sala suele convenir más grande; para habitación tamaño moderado.", relatedCategories: ["televisores"], suggestedFollowups: ["¿Para sala, habitación o negocio?", "¿A qué distancia lo verás?", "¿Priorizas tamaño o precio?"] },
  { id: "smart_tv", label: "Smart TV", aliases: ["smart tv", "tv inteligente", "netflix", "youtube", "apps"], explanation: "Un Smart TV se conecta a internet y usa apps de streaming.", commercialBenefit: "Permite ver contenido sin dispositivos externos.", goodFor: ["casa", "sala", "habitación", "streaming"], limitations: "Depende de internet y compatibilidad de apps.", salesAngle: "Si usa Netflix/YouTube, Smart TV es más práctico.", relatedCategories: ["televisores", "hogar y entretenimiento"], suggestedFollowups: ["¿Lo quieres para Netflix/YouTube?", "¿Es para sala o habitación?"] },
  { id: "guitarra_principiante", label: "Guitarra para principiante", aliases: ["guitarra para empezar", "guitarra para aprender", "primera guitarra", "guitarra basica"], explanation: "Para iniciar, conviene una guitarra cómoda y fácil de tocar, sin inversión alta al inicio.", commercialBenefit: "Ideal para estudiantes o personas que empiezan desde cero.", goodFor: ["principiantes", "clases", "regalos", "estudiantes"], limitations: "Para nivel profesional puede requerir gama superior.", salesAngle: "Para comenzar, priorizar comodidad y confiabilidad antes que lujo.", relatedCategories: ["guitarras", "instrumentos"], suggestedFollowups: ["¿Es para niño, joven o adulto?", "¿Acústica, clásica o eléctrica?", "¿Aprendizaje desde cero?"] },
  { id: "teclado_principiante", label: "Teclado para principiante", aliases: ["piano para aprender", "teclado para aprender", "teclado principiante", "piano principiante"], explanation: "Un teclado para principiante debe ser práctico, fácil de usar y útil para practicar.", commercialBenefit: "Permite iniciar música sin irse de una a un piano costoso.", goodFor: ["niños", "estudiantes", "clases", "práctica en casa"], limitations: "Para estudio avanzado podrían necesitarse funciones más completas.", salesAngle: "Para empezar, un teclado funcional y económico suele ser suficiente.", relatedCategories: ["teclados", "pianos", "instrumentos"], suggestedFollowups: ["¿Niño o adulto?", "¿Clases o casa?", "¿Básico o más completo?"] },
  { id: "cable_audio", label: "Cable de audio", aliases: ["cable de audio", "cable para microfono", "cable para cabina", "cable canon", "xlr", "cable rca", "cable auxiliar"], explanation: "Los cables de audio conectan equipos como micrófonos, consolas, cabinas o instrumentos.", commercialBenefit: "El cable correcto evita ruido y problemas de compatibilidad.", goodFor: ["sonido", "micrófonos", "consolas", "instalaciones"], limitations: "Hay varios conectores; hay que confirmar entradas y salidas.", salesAngle: "Primero se define equipo origen y destino para recomendar el cable exacto.", relatedCategories: ["cables", "sonido", "micrófonos"], suggestedFollowups: ["¿Qué equipo conectarás con cuál?", "¿Tienes foto de las entradas?", "¿Micrófono, consola, cabina o TV?"] },
  { id: "rca", label: "Cable RCA", aliases: ["rca", "cable rca", "rojo blanco", "amarillo rojo blanco"], explanation: "RCA es conexión común de audio/video, usualmente rojo/blanco y a veces amarillo.", commercialBenefit: "Útil para equipos de audio/video doméstico o antiguos.", goodFor: ["audio hogar", "TV", "equipos antiguos"], limitations: "No siempre está en equipos modernos.", salesAngle: "Si ve entradas rojo/blanco, probablemente necesita RCA.", relatedCategories: ["cables", "hogar y entretenimiento"], suggestedFollowups: ["¿Qué colores tienen las entradas?", "¿Lo conectarás a TV o equipo de sonido?"] },
  { id: "hdmi", label: "HDMI", aliases: ["hdmi", "cable hdmi", "entrada hdmi", "conectar tv"], explanation: "HDMI transmite audio y video digital en un solo cable.", commercialBenefit: "Es la forma más práctica para TV, consola, decodificador o PC.", goodFor: ["televisores", "computadores", "consolas", "proyectores"], limitations: "Conviene revisar largo y compatibilidad del cable.", salesAngle: "Para conectar dispositivos al TV, HDMI suele ser la opción correcta.", relatedCategories: ["cables", "televisores"], suggestedFollowups: ["¿Qué dispositivo conectarás al TV?", "¿Qué largo necesitas?"] },
  { id: "car_audio", label: "Car audio", aliases: ["car audio", "sonido para carro", "audio carro", "parlantes carro", "planta carro"], explanation: "Car audio incluye radios, parlantes, plantas, bajos y accesorios para mejorar sonido del vehículo.", commercialBenefit: "Permite subir calidad, volumen, bajo o conectividad Bluetooth.", goodFor: ["carros", "mejora de sonido", "bajo", "bluetooth"], limitations: "Depende de compatibilidad e instalación según el vehículo.", salesAngle: "Primero define si quiere más bajo, volumen o conectividad.", relatedCategories: ["car audio", "parlantes", "amplificadores"], suggestedFollowups: ["¿Qué carro tienes?", "¿Quieres más bajo, volumen o Bluetooth?", "¿Tienes planta o empiezas de cero?"] },
  { id: "instrumentos_salseros", label: "Instrumentos salseros", aliases: ["instrumentos salseros", "campana", "güiro", "guiro", "maracas", "timbal", "percusion salsa", "percusión salsa"], explanation: "Campana, güiro, maracas y timbal se usan para ritmos tropicales y salsa.", commercialBenefit: "Útil para grupos, iglesias, escuelas y aprendizaje musical latino.", goodFor: ["salsa", "grupos", "iglesias", "escuelas", "presentaciones"], limitations: "Cada instrumento requiere técnica distinta según nivel.", salesAngle: "Para iniciar, conviene orientar por nivel y tipo de ritmo.", relatedCategories: ["instrumentos salseros", "percusión"], suggestedFollowups: ["¿Para aprender o tocar en grupo?", "¿Buscas campana, güiro, maracas o timbal?", "¿Para salsa, iglesia o presentación?"] },
  { id: "luz_solar", label: "Luz solar", aliases: ["luz solar", "reflector solar", "lampara solar", "lámpara solar", "panel solar", "energia solar", "energía solar"], explanation: "La luz solar carga en el día y funciona en la noche sin depender directo de la red eléctrica.", commercialBenefit: "Ideal para exteriores donde quieres evitar instalación compleja.", goodFor: ["patios", "entradas", "fincas", "seguridad exterior"], limitations: "Depende de buena exposición solar y batería.", salesAngle: "Si quiere iluminación exterior sin cableado, solar es muy conveniente.", relatedCategories: ["luz solar", "hogar", "seguridad"], suggestedFollowups: ["¿Patio, entrada o finca?", "¿Recibe buen sol?", "¿Buscas seguridad o iluminación general?"] },
];

function normalize(value: string) {
  return (value || "")
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

function escapeRegex(value: string) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function aliasMatches(text: string, alias: string) {
  const probe = normalize(alias);
  if (!probe) return false;
  if (probe.length <= 1) return false;
  if (probe.length <= 2) {
    const pattern = new RegExp(`(^|\\s)${escapeRegex(probe)}(\\s|$)`);
    return pattern.test(text);
  }
  return text.includes(probe);
}

export function findAttributeKnowledge(message: string): KoraAttributeKnowledge | null {
  const text = normalize(message);
  for (const row of KORA_ATTRIBUTE_KNOWLEDGE) {
    if (row.aliases.some((alias) => aliasMatches(text, alias))) return row;
  }
  return null;
}
